language: node_js
node_js:
- 8
deploy:
  provider: npm
  email: charlie@bowtie.co
  skip_cleanup: true
  on:
    tags: true
    repo: bowtie-co/node-react-utils
  api_key:
    secure: QjSYs1ufcIAJNDIgBhrCI6d2cd86UEBC8zOw1E5rTxr3G/3HK6F/ByALxQdF8Muot9itW4mc60hlWsvl20zC3CWNZv4D+Sh4KuQ3GnCwANc8/Ay5JO8OR+MtWtH3rM8OgufkDYU44xRGHTN82GUkw/1H0IzrgBgBZG8wmQ8SMN0hW4e23uLoW1+W3AsbCQLaYXOHvsn480KmNbUm4yFfaujdcup/XAhx6PPHimvRmL7HYDb77BZ6zoFxG5jYcAGvOJnKQ8VsdG5NaXYJxmgFdE027yrjWkIDrBcGS1K9ak0p5uSLhsqI6qXKs6G9wiyGNnOXJZoOBlTeMrUIuOX9iP16XKeJfBmcxpIKp2OI+0gZOIE9d5DzibU3c6J+ptV5A9+CEUJ1uvJNuJbEpNQSKpay4OCznU5sVPvthTlcvIROGyDZZnBKm8rx3WyCTzRDZk0bLv3kyO610xzUsXTAYtVqVM/9WULSrPYKWqXVJ6ewCpxyVRPquZdwj6LD4J6U5X0Ay6q8c7Wpau1nZvPzLeRDQMzqKoxpAQ20/gWDUoiF375PPq2lSl5KTAnwME6Tww7kNSjCT7Q0QIwSxFZSMn52wJ3Qx+LuZfkhSv3f/EGFnR9mN0GTySKc/Ndxi9NVbhWZAtPj/wZBosLJaNljRgcS943XwTRFw1fcipojkTc=
notifications:
  slack:
    secure: Ly5Tpx7Gm2PV18Cs9Hdlb7gOeeocdee04n54eUNMG+ighIISY88DOGttQKlgn6S9lTYtp50zUb32X7iGiEOFcTOKzMcN/FAFJtsJLOwoF4M3eSrN2aKqhmsFJNj2YZWnKoqYT4V1PmD20noYBuO3X0ECnD5o+5ZQOQ4X+L0IRLlWg9ExR7LD4dYuk6r8mbxOIy0F1szfPbZ+6tGusNhxl6IQk/RaUOmYTapD/rjx4DQX94QVssYTHibn4EvktA9xOu6/qGC4jzNgLyBChagrX+ppbbYC/pyV14rInYG2gTTIIhpIXk/RnQQ43K8XNUnmuVbNdSoCodGAOv3V69uULxbegut39oRHDuysVlgR/dFqmjYOYV+FDxjVkr0Z3VdQlSfTjrh7Ezg87yvhnHWXRN4p0YzmC7/QZV6wcECua1QqnPIrVMnNf1veTgLu7nN/ZxbigL5WmQC6F8NkcUhR6832A7A/SCwbQEmoEj4PQlAVOgly9jqwWvHQyDad7+tbVFgchb51lWtJ7P6qClcz/a0KsMuUf2wW4VJWPbaX9f499Ixe5DT0ppZQcvF3chdVj1jlxnN7Kc1t3nV2CInL6fGsTtRB4xkUGFs9YhNs3GsJ3w8wGbNVUSEX+WbVJH+pLHfRStB+fevtue1UzyrNezn0cHE064diS87McmXkcCI=
